import type { Metadata } from "next";
import { 
  inter,
  roboto_condensed,
  racing_sans_one,
  league_spartan,
  roboto_mono,
  montserrat,
  open_sans,
  raleway,
  bebas_neue,
  lato,
  kaushan_script,
  comic_neue,  
} from "@/lib/fonts";
import "../globals.css";
import { ReduxProvider } from "@/redux/ReduxProvider";


export const metadata: Metadata = {
  title: "TapUp | Profile",
  description: "Generated by create next app",
};

export default function BuilderLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={`${inter.className} ${roboto_condensed.variable} ${racing_sans_one.variable} ${league_spartan.variable} ${roboto_mono.variable} ${montserrat.variable} ${open_sans.variable} ${raleway.variable} ${bebas_neue.variable} ${lato.variable} ${kaushan_script.variable} ${comic_neue.variable}`}>
        <section className="w-full overflow-x-hidden layout-rout">
          <div className="relative z-0">
            <ReduxProvider>
              {children}
            </ReduxProvider>      
          </div>
        </section>
      </body>
    </html>
  )
}