import type { Metadata } from "next";

import {
  inter,
  roboto_condensed,
  racing_sans_one,
  league_spartan,
  roboto_mono,
  montserrat,
  open_sans,
  raleway,
  bebas_neue,
  lato,
  kaushan_script,
  comic_neue,
} from "@/lib/fonts";
import "../globals.css";
import DesktopSidebar from "@/components/dashboard/DesktopSidebar";
import { Suspense, useEffect } from "react";
import DashboardNav from "@/components/dashboard/DashboardNav";
import MobileNavbar from "@/components/dashboard/MobileNavbar";
import Loader from "@/components/Common/Loader";
import QueryProvider from "@/lib/QueryProvider";
import { IsAuth } from "@/lib/auth/AuthProvider";

export const metadata: Metadata = {
  title: "TapUp | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${roboto_condensed.variable} ${racing_sans_one.variable} ${league_spartan.variable} ${roboto_mono.variable} ${montserrat.variable} ${open_sans.variable} ${raleway.variable} ${bebas_neue.variable} ${lato.variable} ${kaushan_script.variable} ${comic_neue.variable}`}
      >
        <QueryProvider>
          <IsAuth>
            <section className=" dashboard-container ">
              <DesktopSidebar />
              <div>
                <DashboardNav />
                <main className=" min-h-screen bg-custom-gray md:ml-[50px] md:p-4 lg:ml-[265px]">
                  <Suspense fallback={<Loader />}>{children}</Suspense>
                </main>
              </div>
              <MobileNavbar />
            </section>
          </IsAuth>
        </QueryProvider>
      </body>
    </html>
  );
}
