import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import DesktopSidebar from "@/components/dashboard/DesktopSidebar";
import { Suspense } from "react";
import DashboardNav from "@/components/dashboard/DashboardNav";
import MobileNavbar from "@/components/dashboard/MobileNavbar";
import Loader from "@/components/Common/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TapUp | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <section className=" dashboard-container ">
        <DesktopSidebar />
        <div>
          <DashboardNav />
          <main className=" min-h-screen bg-custom-gray md:ml-[50px] md:p-4 lg:ml-[265px]">
            <Suspense fallback={<Loader />}>
              {children}
            </Suspense>
          </main>
        </div>
        <MobileNavbar />
      </section>
      </body>
    </html>
  );
}
